### ISSUE TITLE
Optimize handling of temp files (vs --cleanup)

### ISSUE THREAD

**Issue by rscottbailey** [godaddy/tartufo#11]
This annoys me so much. ;-)

1. Can we make `--cleanup` the default behavior, at least if no findings are found? It makes no sense that 99.999% of the time the repo is clean and the scratch directory is empty, why should the user have to expend extra effort to remove the empty directory?

Frankly, I'm not sure that --cleanup shouldn't be the default all the time, anyway. Findings are reported on stdout anyway, so the utility here seems to be the case where you expect to have massive numbers of findings and want to save them conveniently for later review.

My proposal would be this:
* eliminate `--cleanup` (both the command flag and the `util.clean_outputs()` function)
* push creation of `output_dir` from scanner's `find_staged()` and `find_strings()` into `handle_results()` where it is done on a just-in-time basis when needed
* add a new flag like `--save-to-dir` which enables calling `handle_results()`, and which defaults to false/none, which means we never call `handle_results()` unless the user asks to save the files, and never create the directory unless we have something to put into it.

2. In addition to, or alternatively, could we at least include "tartufo" in the name (say as a prefix argument to `mkdtemp`)?

**Comment by decompil3d** [comment]
Nit: `-o` is often used in other packages (e.g. aws cli, kubectl) for output format, not output location. Can we consider using something like `--out-dir`/`-od`?

**Comment by rscottbailey** [comment]
Very satisfied customer. ;)

**Comment by tarkatronic** [comment]
This isn't closed quite yet! I'm going to leave this open just until #82 gets merged. Just in case. And then this will auto-close with that PR. 😄

**Comment by tarkatronic** [comment]
@rscottbailey Any chance you can help out with a review of #82 to make sure it works as expected?
