### ISSUE TITLE
Local scans fetch remote origin

### ISSUE THREAD

**Issue by jgowdy** [godaddy/tartufo#118]
## 🐛 Bug Report

When using the "scan-local-repo" command, tartufo still tries to fetch remote origin:

`branches = self._repo.remotes.origin.fetch()`

## To Reproduce

`tartufo scan-local-repo .`

Observe that tartufo helps itself to my remotes and attempts to fetch origin

## Expected Behavior

Local repo scans only utilize the local working copy and git database locally.

**Comment by jgowdy** [comment]
I believe the issue is here:
```python
            if self.git_options.branch:
                sys.stderr.write("Fetching remote origin for branch " + self.git_options.branch + "\n")
                branches = self._repo.remotes.origin.fetch(self.git_options.branch)
            else:
                sys.stderr.write("Fetching remote origin\n")
                branches = self._repo.remotes.origin.fetch()
```
Unconditionally using remote branches, even if we've specified scan-local-repo

If I comment out the above code and do
```python
            branches = self._repo.branches
```

It seems much faster.

**Comment by jgowdy** [comment]
Fixed in https://github.com/godaddy/tartufo/pull/119

**Comment by tarkatronic** [comment]
For the record, here is where this behavior originates: https://github.com/dxa4481/truffleHog/blob/dev/truffleHog/truffleHog.py#L314-L317
