### ISSUE TITLE
Publish the Python package of Tartufo to https://github.com/godaddy/tartufo/packages

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#128]
## Is your feature request related to a problem? Please describe.

Publish the Python package of Tartufo to https://github.com/godaddy/tartufo/packages

## Describe the solution you'd like

Add additional CICD steps to publish to the GitHub package repository in addition to existing ones

## Describe alternatives you've considered

n/a

## Teachability, Documentation, Adoption, Migration Strategy

This will allow consumers of Tartufo to pull it directly from GitHub, as a Python package, if they wish without having to go to pypi.org or dockerhub

**Comment by tarkatronic** [comment]
Sadly, this is not yet possible :( https://github.com/github/roadmap/issues/94

This is currently slated as a "Future" item in GitHub's [roadmap](https://github.com/github/roadmap/projects/1#card-42486677), so it looks like Q3 2021 is the earliest it would get done.
