### ISSUE TITLE
Publish a GitHub Action for Tartufo on the GitHub Action Marketplace

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#129]
## Is your feature request related to a problem? Please describe.

n/a

## Describe the solution you'd like

Publish a GitHub Action for Tartufo on the GitHub Action Marketplace

## Describe alternatives you've considered

n/a

## Teachability, Documentation, Adoption, Migration Strategy

With the adoption of GitHub Actions by GitHub users this would provide a simple way for them to consume the tool without having to set up anything special in their codebase

**Comment by c-jcarlsen-godaddy** [comment]
The new scan-local option would also allow a tartufo github action to run without providing it a PAT and just use the built in shallow clone in GitHub Actions default instead (actions/checkout)

**Comment by sushantmimani** [comment]
A GitHub action for Tartufo now exists at https://github.com/godaddy/tartufo-action
