### ISSUE TITLE
Include/Exclude Path Patterns inside `[tool.tartufo]` TOML

### ISSUE THREAD

**Issue by rdrey** [godaddy/tartufo#145]
## Is your feature request related to a problem? Please describe.

I'd like to keep `tartufo` config in a single file and need to maintain separate files with `exclude-paths`/`include-paths` at the moment.

## Describe the solution you'd like

I'd like it if I could specify `exclude-paths` in a list inside the config TOML, just like `exclude-signatures`. 

Since the parameter is currently a file type in the `click.option` we could

1. introduce another parameter that is always a list of exclusion patterns, `exclude-path-patterns`?
1. Make `--exclude-paths` behave differently if given once (read file for patterns) or multiple times (each invocation is a pattern). This is probably too messy, difficult to explain.

## Describe alternatives you've considered

Naming my excludes `.tartufo-excludes`, just like in this repo, to be grouped with other .dotfiles. That list is getting long. Or tucking it deeper into the `conf/` directory of my repo, which is currently more for operational service config.

## Teachability, Documentation, Adoption, Migration Strategy

If we add a new parameter it would have to be mentioned in the Readme, CLI help, etc. Adding a new parameter should have zero impact on the old use case. We could update docs of `exclude-paths` to mention the new parameter, potentially deprecate the separate files down the line.

**Comment by rdrey** [comment]
I'd be happy to work on this if others agree that it's a good idea.

**Comment by tarkatronic** [comment]
@rdrey I love this idea! I've actually been tossing this idea around in my head for a while now, so I'm happy you filed this.

Good call also on the new parameter name.

I think the real challenge here will be the modifications to the options and making sure to cleanly merge all potential paths for adding these patterns. Specifically:

* Command line / config file legacy patterns
* Command line / config file new style patterns
* Target repo config file legacy patterns
* Target repo config file new style patterns

Happy to work with you on this; feel free to hop into the #tartufo channel on the GoDaddyOSS Slack if you want to talk about it more!

We also have a mailing list now if you would like to use that as well 😄 https://groups.google.com/g/tartufo-secrets-scanner
