### ISSUE TITLE
Show progress in the terminal

### ISSUE THREAD

**Issue by sgore-godaddy** [godaddy/tartufo#148]
## Feature Request
Show progress in the terminal when running the scan

## Is your feature request related to a problem? Please describe.

It is not a problem, but an enhancement request. 
When running a full repo scan with a lot of branches and tags with a large commit history it takes a while for the scan to complete. Sometimes I feel like it is stuck (when actually it isn't).

## Describe the solution you'd like

So as to give visual feedback that it is actually scanning and it is not stuck, some kind of visual progress indicator will be good to have. 
Ideal would be if it can show a % completion (or time remaining), just a spinning `/` would also be good. 

## Describe alternatives you've considered

None

**Comment by dboonzaier-godaddy** [comment]
@sgore-godaddy I'm just wondering if this is _almost_ a duplicate of (or at least related to) https://github.com/godaddy/tartufo/issues/76 and https://github.com/godaddy/tartufo/issues/42?

At any rate, I know in our team this is a highly requested feature.

**Comment by tarkatronic** [comment]
@sgore-godaddy Providing an accurate percent complete is difficult. The last thing I want to do is introduce a classic Microsoft progress bar that takes 2 hours to complete what's labeled as 4 minutes. It might be interesting to see if we can determine the total number of commits to be scanned somehow... then we could use something like https://github.com/tqdm/tqdm to show progress.

For now though I am working on adding logging via #167 -- so this might be enough to at least help you for now. If you look [at this comment](https://github.com/godaddy/tartufo/pull/167#issuecomment-778247436), it's got an example of the output. You will also be able to use `-vvv` for even more output, down to showing each diff being processed.

**Comment by tarkatronic** [comment]
@sgore-godaddy I just added logging in #167, and this should be getting released soon. Do you think this will work for what you were wanting? Or were you looking for something else?

**Comment by sgore-godaddy** [comment]
@tarkatronic  yes the logging would work.
