### ISSUE TITLE
Specifying the "--branch {branchName}" option when running "tartufo scan-local-repo" never reports findings

### ISSUE THREAD

**Issue by dboonzaier-godaddy** [godaddy/tartufo#158]
## 🐛 Bug Report

When running `tartufo scan-local-repo --branch {branchName} .` no findings are reported and the tool finishes with the standard 0 (all clear) exit code. 

Even though there are indeed high entropy strings committed to the target branch. This is confirmed by the fact that if you run `tartufo scan-local-repo .` the offending strings are reported.

And as such it appears as if specifying the `--branch {branchName}` option results in no findings being detected.

**Please note that this does not appear to be the case V2.0.2. So it seems this bug was introduced recently.**

## To Reproduce

1. Create and switch to a new branch {branchName}
2. Add an offending string to any file (not included in the `exclude-paths`) in your branch
3. Git add the file to your current branch
3. Run `tartufo pre-commit` to confirm that the `pre-commit` detects that string
4. Git commit the file containing the offending string to your branch
5. Now run `tartufo scan-local-repo --branch {branchName}` you will notice that the string is not detected

## Expected Behavior

When using the `--branch {branchName}` option with the `tartufo scan-local-repo` command. All findings in the target branch are reported.

## Environment

```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2,4 GHz
  
System Software Overview:

  System Version:	macOS 10.15.7 (19H15)
  Kernel Version:	Darwin 19.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
```

```
python -V
Python 2.7.16
```

```
tartufo -V
tartufo, version 2.2.1
```

tartufo.toml
```
[tool.tartufo]
repo-path = "."
cleanup = true
regex = true
entropy = true
exclude-paths = ".tartufo-excludes"
exclude-signatures = [ ]
```

.tartufo-excludes
```
go.mod
go.sum
pyproject.toml
tartufo.toml
```

**Comment by riggaroo** [comment]
@tarkatronic Could you give a bit more information as to how the --branch option is supposed to work? I am using version 2.4.0 but it seems like it still runs through all the commits on the base branch too ie I have a branch from develop, and I was expecting the scan to only run on the commits that are on the particular branch, but it seems that it also runs on the base branch too.
