### ISSUE TITLE
Docker container invocation is not functioning

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#165]
## 🐛 Bug Report

Previously working workflows calling the docker Tartufo image are now failing

## To Reproduce
Invoke Tartufo docker image from GH action workflow:

> Run ./tartufo
> Building docker image
> /usr/bin/docker run --name d857a1aeaec526760215ab12ba8e6a8_fe6bb9 --label 442333 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_OPTIONS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/tartufo/tartufo":"/github/workspace" 442333:<snip>
> /entrypoint.sh: line 14: /venv/bin/tartufo: not found

## Expected Behavior

Successfully executes

## Code Example

> name: Tartufo scan for secrets
> 
> on: [push, pull_request]  # Trigger on all pushes to all branches
> 
> jobs:
>   tartufo:
>     runs-on: ubuntu-latest
>     steps: 
>     - name: Checkout this repo
>       uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
snip
>       with: 
>         repository: <snip>/tartufo
>         token: ${{ secrets.REPO_CLONE_TOKEN }} # PAT with read access to <snip>/tartufo
>         path: tartufo
>         persist-credentials: false # Do not persist auth token in local git config.
>     - name: Run Tartufo from <snip>/tartufo repository
>       uses: ./tartufo
>       with:
>         github_token: ${{ secrets.REPO_CLONE_TOKEN }}

## Environment

n/a

**Comment by mxhenry-godaddy** [comment]
@tarkatronic Can you sanity check this for me please? @jmink-godaddy , @c-jcarlsen-godaddy and myself were looking into this yesterday.

I think the resolution is replacing `/venv/bin/tartufo` with just `tartufo`

**Comment by mxhenry-godaddy** [comment]
hrm, the `/venv/bin/tartufo` works if I build locally

**Comment by tarkatronic** [comment]
I can't find any problems in the recent docker build that stand out to me as problematic: https://github.com/godaddy/tartufo/runs/1832676464?check_suite_focus=true

Can you confirm the last working version, and when this started to break?

**Comment by tarkatronic** [comment]
Also, where did the `d857a1aeaec526760215ab12ba8e6a8_fe6bb9` tag come from? Looking at the latest release [on Docker hub](https://hub.docker.com/layers/godaddy/tartufo/2.3.0/images/sha256-289b1e49f564a0118345da229960986a61e81d6eeb13be7cf0512e1343c7cc3a?context=explore), that doesn't appear to match.

**Comment by mxhenry-godaddy** [comment]
I'm not sure where the workflow execution is getting that from.

**Comment by mxhenry-godaddy** [comment]
This might be a chicken/egg problem on the repo using the tartufo docker
