### ISSUE TITLE
pre-commit ignores tartufo.toml exclude_signatures when run in pre-commit hook

### ISSUE THREAD

**Issue by dkoopman-godaddy** [godaddy/tartufo#204]
## 🐛 Bug Report

Adding signatures to tartufo.toml works fine with running manually like this:
tartufo --regex --entropy pre-commit

However, when run through pre-commit via .pre-commit-config.yaml, it seems to ignore the exlude-signatures and continues to alert on these items. 

## To Reproduce

Inside your repo that has pre-commit installed with tartufo hook, first make sure your 
.pre-commit-config.yaml
```
repos:
- repo: https://github.com/godaddy/tartufo
  rev: v2.6.0
  hooks:
  - id: tartufo
    entry: tartufo --regex --entropy
```
Then:
```
echo "var url = 'https://fakeUser:fakePassW0rd@fakeurl.int.godaddy.com'" > fakeUrl.js
git add fakeUrl.js
git commit -m "fakeUrl.js"
```
The output of this git commit should look something like this:
```
Tartufo..................................................................Failed
- hook id: tartufo
- exit code: 1
 
~~~~~~~~~~~~~~~~~~~~~
Reason: Regular Expression Match
Detail: Password in URL
Filepath: fakeUrl.js
Signature: 3513753586166dd78bf032124692f507d0cebc1b9a923cb087005117eff09187
@@ -0,0 +1 @@
+var url = 'https://fakeUser:fakePassW0rd@fakeurl.int.godaddy.com'
 
~~~~~~~~~~~~~~~~~~~~~
```
Then take the Signature, in this case 3513753586166dd78bf032124692f507d0cebc1b9a923cb087005117eff09187 and add it to tartufo.toml as a signature. Then
```
tartufo --regex --entropy pre-commit
# See how this ^ works fine, excludes the issue fine
```
Then:
```
git commit -m "fakeUrl.js"
```
Pre-commit ^^ will flag this, even though the signature is in tartufo.toml

## Expected Behavior

Pre-commit will honor the tartufo.toml file and exclude the signatures

## Code Example

N/A

## Environment

using 2.6.0

**Comment by tarkatronic** [comment]
Hi @dkoopman-godaddy, thanks for reporting this issue! Can you please try `git add tartufo.toml` along with your `fakeUrl.js`? I suspect this is not so much a bug in tartufo, but actually an expected behavior with the way that git and `pre-commit` work. Specifically, before the hook is run, any unstaged changes are stashed, and therefore no longer visible until after the hook runs.

**Comment by dkoopman-godaddy** [comment]
@tarkatronic Right on!
```
 ❯❯❯ echo "var url = 'https://fakeUser:fakePassW0rd@fakeurl.int.godaddy.com'" > fakeUrl.js
 ❯❯❯ git add fakeUrl.js
 ❯❯❯ git commit -m "fakeUrl.js"
Tartufo..................................................................Failed
- hook id: tartufo
- exit code: 1

~~~~~~~~~~~~~~~~~~~~~
Reason: Regular Expression Match
Detail: Password in URL
Filepath: fakeUrl.js
Signature: 3513753586166dd78bf032124692f507d0cebc1b9a923cb087005117eff09187
@@ -0,0 +1 @@
+var url = 'https://fakeUser:fakePassW0rd@fakeurl.int.godaddy.com'

~~~~~~~~~~~~~~~~~~~~~

 ❯❯❯ vim tartufo.toml # added 3513753586166dd78bf032124692f507d0cebc1b9a923cb087005117eff09187
 ❯❯❯ git add tartufo.toml
 ❯❯❯ git add tartufo.toml
 ❯❯❯ git commit -m "fakeUrl"
Tartufo..................................................................Passed
[master 2e29408] fakeUrl
 2 files changed, 2 insertions(+)
 create mode 100644 fakeUrl.js
```
