### ISSUE TITLE
Tartufo scanning issue on window

### ISSUE THREAD

**Issue by spatil-godaddy** [godaddy/tartufo#211]
## 🐛 Bug Report
when trying to scan GIT repo on window machine using ```tartufo scan-local-repo .``` command. i am getting below issue
![image](https://user-images.githubusercontent.com/72795229/129929114-8ac7abd5-1189-445e-929e-99902e2e3270.png)

i feel, might be one of the file have UTF-8 characters which tartufo not able to read

## To Reproduce

Add UTF8 character in file and scan it ( specially Chinese characters like 开始搜  )

## Expected Behavior

scanning should complete on Window machine

**Comment by tarkatronic** [comment]
Hi @spatil-godaddy, thank you for filing this report! Are you able to share the contents of your `tartufo.toml` so that we can understand all arguments that tartufo is being run with?

**Comment by tarkatronic** [comment]
@spatil-godaddy We've been having trouble reproducing this... it appears that Python is attempting to open stdout with the CP-1252 encoding; unfortunately we haven't yet been able to figure out how or why.

Just guessing at things here, what is the encoding of the file causing problems, and what is the result of `echo $LANG` in your shell?
