### ISSUE TITLE
How-To Publish Site Content Using GitHub-Actions ... Help? Or Documentation? Thanks :)

### ISSUE THREAD

**Issue by Uhfai3000** [godaddy/tartufo#228]
GitHub Issues in `godaddy/tartufo` repository are used exclusively for tracking
bugs in Tartufo. Please do not submit support requests through GitHub. Bugs are
inherent software issues or problems potentially affecting anyone who uses this
project, whereas support request are unique issues experienced by the consumer.
If you have doubts whether a problem is a bug or support request feel free to
reach out to contributors on [slack] or the [Tartufo Mailing List]. They'll guide you in the process.

For questions or help, please see:

- The [README] file
- [GoDaddy's OSS slack][slack]
- The [Tartufo Mailing list]

### Please note that this issue tracker is not a help forum and requests for help will be closed.

[Slack]: https://godaddy-oss.slack.com/
[README]: https://github.com/godaddy/tartufo/blob/main/README.md
[Tartufo Mailing list]: https://groups.google.com/g/tartufo-secrets-scanner

**Comment by tarkatronic** [comment]
Not an issue related to tartufo.
