### ISSUE TITLE
Change toml parsing library to use `tomlkit`

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#231]
Currently tartufo uses the [toml](https://github.com/uiri/toml) library for our parsing. This has worked great until now, but we are starting to reach the limits of the library. And unfortunately, it seems to be unmaintained currently. The last commit to the library was in October 2020, and I have encountered a bug (https://github.com/uiri/toml/issues/270) which could impede our progress on future features.

[tomlkit](https://github.com/sdispater/tomlkit), on the other hand, is actively maintained by sdispater, the primary author/maintainer of the Poetry project. In fact, it is the TOML parser used for Poetry itself. So we can be assured that it will remain stable. In addition, we will be able to use this library in the future for writing back to the configuration file while preserving all pre-existing style, structure, etc!

**Comment by ErikOwen** [comment]
Hi @tarkatronic, can I take this issue?

**Comment by tarkatronic** [comment]
Hi @ErikOwen! That would be great, thank you for volunteering!

I will warn you up front, this is a pretty high priority change for us, so I may have to yank it back if you're unable to make progress in the next couple of weeks. But, as long as you have the time and bandwidth, I would absolutely welcome the contribution!
