### ISSUE TITLE
Remove the `--fetch`/`--no-fetch` options in v3.0

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#240]
## Is your feature request related to a problem? Please describe.

The `--fetch`/`--no-fetch` functionality is just weird. It only exists because it has existed since forking from `truffleHog`. It should no longer exist.

## Describe the solution you'd like

The options are completely gone!

## Describe alternatives you've considered

Switching the default to `--no-fetch`. But really I see no reason to leave it in at all. It should just go away. Users can easily `git fetch` before running tartufo, and then they have better control without weird side effects.

## Teachability, Documentation, Adoption, Migration Strategy

We may want to put a note into 2.x docs that this option is being deprecated and will be removed in v3.0.

**Comment by sushantmimani** [comment]
Closed by #241
