### ISSUE TITLE
Tartufo does not generate correct git content in issue descriptions

### ISSUE THREAD

**Issue by rbailey-godaddy** [godaddy/tartufo#243]
## 🐛 Bug Report

Tartufo output (using v3.x branch or scan-bugfix branch) is total garbage. If for example you try

```sh
tartufo scan-local-repo . --no-fetch | more
```
and then take the commit hash listed in the generated issue and look at it i.e.

```sh
git show 1e05550db11b235725c205172cb64c1bdbcea5ec
```

you will see that (a) the diffs are completely different and involve different files and (b) the actual diff (reported by git) does not contain the dubious material that caused the issue to be generated.

Looking at

```sh
$ git log --oneline | grep -B5 -A5 1e05550
e4a947f Correct content type for the package description
90fceca Docker build (#25)
ec76899 Let he PyPi password trickle in from Travis
73147cb Reworked the Travis config again (#24)
6e34275 Split the code into multiple discrete modules (#22)
1e05550 Fix up the Travis config (#23)
d0a2447 Pre commit hooks (#21)
20ce179 Fix import of truffleHogRegexes (#20)
f1be7a4 Cleanup round 1 (#16)
e7e98de Additive whitelist/blacklist support (#9)
adf5b48 Update README.md
```

to see the surrounding commits (assuming this order matches tartufo's processing order), it appears possible that this is an "off-by-one" error where you are generating the diff going in the wrong direction relative to the actual commit point, but that is an educated long-short guess.

## To Reproduce

```sh
git checkout scan-bugfix
tartufo scan-local-repo . --no-fetch
```

## Expected Behavior

The information reported by `git show <hash-of-reported-commit>` should match the diff reported by tartufo.

## Environment

What you see above -- no local configuration file beyond what's there by default in the repository.

**Comment by sushantmimani** [comment]
Fixed by #241
