### ISSUE TITLE
Remove `--include-paths` and `--exclude-paths` in v3.0

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#255]
## Is your feature request related to a problem? Please describe.

The `-i` / `--include-paths` and `-x` / `--exclude-paths` options have been deprecated since v2.5.0 and should be removed.

## Describe the solution you'd like

`-i` / `--include-paths` and `-x` / `--exclude-paths` options are completely removed.

**Comment by emayuri-godaddy** [comment]
The issue is addressed in https://github.com/godaddy/tartufo/pull/276
