### ISSUE TITLE
Change `--b64-entropy-score` and `--hex-entropy-score` to `--entropy-sensitivity`

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#265]
## Is your feature request related to a problem? Please describe.

The `--b64-entropy-score` and `--hex-entropy-score` arguments, while useful, can be very confusing. Even knowing the internals of tartufo like I do, I can't say with complete confidence what the default values represent, nor how they were arrived at.

## Describe the solution you'd like

As described by @rbailey-godaddy in https://github.com/godaddy/tartufo/pull/223#issuecomment-934404699, it would be far more useful and intuitive to have a `--entropy-sensitivity` argument, ranging from 1-100. It would require a bit more calculation on the part of tartufo, but would then be much more understandable for users.

The one thing I'm unsure of is, should this be split out into `--b64-entropy-sensitivity` and `--hex-entropy-sensitivity`, or keep them combined as one?

**Comment by rbailey-godaddy** [comment]
> The one thing I'm unsure of is, should this be split out into `--b64-entropy-sensitivity` and `--hex-entropy-sensitivity`, or keep them combined as one?

I strongly advocate keeping them combined as one thing. They are effectively linked by the underlying math and the difference between them is due solely to the size of the representation character set. To my mind, wanting to use different settings for each representation is like standing in the surf at the beach and thinking "this water is too cold for my left foot and too warm for my right foot". ;-)

**Comment by tarkatronic** [comment]
Fixed in #272
