### ISSUE TITLE
Write a guide for upgrading from v2 -> v3

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#279]
## 📃 Summary

The change from v2 to v3 is going to be a significant one. Tartufo will be more accurate, VASTLY faster, and the configuration is going to change a good bit. What we need to do is make a best effort to ease this transition for our users.

## Expected documentation

We need to write up a clear, step-by-step guide on what changes users can expect, and how to prepare themselves for the upgrade from v2.x -> v3.0.

**Comment by rbailey-godaddy** [comment]
Fixed by #288
