### ISSUE TITLE
Add trojan packages to blacklist

### ISSUE THREAD

**Issue by rscottbailey** [godaddy/tartufo#28]
# Feature Request

In addition to flagging disclosure of secrets, we could leverage tartufo to flag usage of known-bad libraries etc.

## Is your feature request related to a problem? Please describe.

Regarding https://www.zdnet.com/article/two-malicious-python-libraries-removed-from-pypi/ which identifies `python3-dateutil` and `jeIlyfish` (note funky spelling of the latter), it seems useful to blacklist these names so we'd catch any accidental usage.

## Describe the solution you'd like

Add these package names to list of blacklisted expressions.

## Describe alternatives you've considered

I haven't considered alternatives -- this is a knee-jerk response. ;-)

## Teachability, Documentation, Adoption, Migration Strategy

As a bonus, it would be nice if we were able to explain why these strings are blacklisted, but that presumably would require more infrastructure than just adding them to the existing blacklist.  It is unfortunate that a user, seeing tartufo scream about "python3-dateutil" (for example), really won't have any idea why the error is being raised.

One approach might be to have multiple lists and report the name of the list as part of the finding, so that you might see "PGP secret key (default blacklist)" and "python3-dateutil (trojan blacklist)" tags or something similar. (Or just reformulate the existing list to include a tag/description/explanation with each pattern.)

**Comment by rscottbailey** [comment]
Rrrr. I notice subsequent discussion mentioning the python3-dateutil package on Debian derivatives (installed with apt or friends), not to be confused with the (evilish) python3-dateutil library (installed with pip). Therefore we'd probably need to look for something like "pip.*python3-dateutil" to distinguish specifically the pypi package...

**Comment by tarkatronic** [comment]
My gut reaction here is to say that this is out of scope for tartufo. A simple string search for these would not necessarily be effective, and could cause either confusion as you mentioned, and/or a false sense of security. Take, for example, the fact that numerous Linux distributions have legitimate packages named `python3-dateutil`, and you have a high potential for false positives. There is also the case of indirect dependencies; while my code may not directly reference the offending packages, something further down my dependency tree may. So then we get into the world of deep dependency scanning, which should definitely be left to another tool.

Finally, and this isn't necessarily a blocker in itself, but these strings are hyper specific, only applying to code in one language. This is a pattern which has been avoided so far, and I think it's important to maintain that. That is, until we start thinking about sub-packages like `tartufo-python-scans`, etc.

**Comment by tarkatronic** [comment]
I'm going to go ahead and close this as it appears to be pretty well out of scope for this project. Feel free to reopen if you still think this could be fit in here. :smile:
