### ISSUE TITLE
Command to Upgrade Config to 3.x

### ISSUE THREAD

**Issue by dclayton-godaddy** [godaddy/tartufo#313]
## Is your feature request related to a problem? Please describe.

Upgrade to 3.0 has caused tedious configuration changes. 

## Describe the solution you'd like

Would love if there was a command like `tartufo config --upgrade-3x` to upgrade to the new format.

## Describe alternatives you've considered

Manually updating.

**Comment by sushantmimani** [comment]
A new `tartufo update-signatures` command was added in v3.1.2. #368
