### ISSUE TITLE
Option exclude-findinds, mentioned in README, does not exist

### ISSUE THREAD

**Issue by paulodiovani** [godaddy/tartufo#357]
## 🐛 Bug Report

The README includes the following usage text:

> ```
>   -e, --exclude-signatures TEXT   [DEPRECATED] Use the exclude-findings config
>                                   option instead. Specify signatures of
>                                   matches that you explicitly want to exclude
>                                   from the scan, and mark as okay. These
>                                   signatures are generated during the scan
>                                   process, and reported out with each
>                                   individual match. This option can be
>                                   specified multiple times, to exclude as many
>                                   signatures as you would like.
> ```

Notice the

> [DEPRECATED] Use the exclude-findings config

But the `exclude-findings` option does not exist anywhere in code:

```
 🥑  tartufo   main  rg exclude-findings
README.md
86:  -e, --exclude-signatures TEXT   [DEPRECATED] Use the exclude-findings config
```

Either the README is outdated, or the code is.

**Comment by sushantmimani** [comment]
Hi @paulodiovani. This has been fixed in the latest main and Tartufo v3.1.4.
