### ISSUE TITLE
Remove log location output if no security risks are detected

### ISSUE THREAD

**Issue by matcartmill-old** [godaddy/tartufo#37]
## Is your feature request related to a problem? Please describe.

No.

## Describe the solution you'd like

By default, when no security risks are discovered Tartufo should not output a log location. This should be opt-in using a `--output-log-location` flag.

## Describe alternatives you've considered

Nothing.

## Teachability, Documentation, Adoption, Migration Strategy

I envision something like `tartufo --regex --output-log-location` to show log location when no risks are found. Otherwise, no output when no risks are found.

**Comment by tarkatronic** [comment]
I'm not sure a new flag is the best solution here. I think our best option is likely to treat this as a bug and simply remove the message if the files are not saved.

**Comment by tarkatronic** [comment]
This got resolved in #82
