### ISSUE TITLE
Add support for tagging repository with scan results

### ISSUE THREAD

**Issue by rscottbailey** [godaddy/tartufo#41]
## Feature Request

After scanning a repository with tartufo, I would like to add an assertion to the repository that a scan was completed (successfully). Presumably this assertion would include the tartufo version and arguments.

## Is your feature request related to a problem? Please describe.

Suppose I am migrating a repository to a new environment. I, the owner, will have run tartufo to ensure the repo is "clean" prior to migration. It would be nice to avoid re-running a potentially time- and resource-intensive full history scan.

## Describe the solution you'd like

* When a scan completes and finds no problems, it optionally creates a tag (or whatever) in the target repository that asserts this fact.
* Finding a tartufo assertion in the commit history (as a tag?) would be more convenient and at least or more secure than communicating a head commit OOB and claiming "it's clean"
* (scope creep already!) Optionally, subsequent tartufo scans could be short-circuited by not progressing backwards in time beyond an encountered successful scan assertion.

This presents an open problem (caveat emptor) regarding treatment of encountered scan tags:

* Do I trust the person who created the tag (not to have falsified it)?
* Do I like/accept (or can I even see) the flags used by the scan?

## Describe alternatives you've considered

I haven't, really. But "repeating scans in their entirety to trust-but-verify" seems heavy-handed, and "well just email me a commit and tell me you did it" seems a little flaky.

## Teachability, Documentation, Adoption, Migration Strategy

Probably something like:

```bash
tartufo --tag-if-passed ...
```

and optionally

```bash
tartufo --stop-at-previous-scan ...
```

**Comment by tarkatronic** [comment]
My initial gut check on this is one of hesitance. I'm not sure I can fully articulate why right now, though. I think partially because it wouldn't be terribly difficult to achieve this behavior currently, by using the `--since-commit` flag. You could do something like:

```sh
# First run
$ tartufo --regex --entropy && echo `git rev-parse HEAD` > tartufo-latest-scanned
# Subsequent runs
$ tartufo --regex --entropy --since-commit `cat tartufo-latest-scanned`
```
Alternatively, you could even take the output of `git rev-parse HEAD` (let's say `d3a2ec3b827651eeaf097f5eff09aaceaa26a914` for example, and place that into the config file, like so:

```toml
[tool.tartufo]
since-commit = "d3a2ec3b827651eeaf097f5eff09aaceaa26a914"
```

This would guarantee that any subsequent scans would not scan earlier commits than the one designated here.

**Comment by tarkatronic** [comment]
@rscottbailey I'm going to close this as `wontfix` given the reasons in my comment above.
