### ISSUE TITLE
Report output on clean or successful scan

### ISSUE THREAD

**Issue by tcostello-godaddy** [godaddy/tartufo#42]
## Feature Request

Need output to screen and or text file when scan results are clean.

Example:
scan run: 02-20-2020 
scan result: 100% Clean. Success

or

'02/20/2020 - 100% Clean'

## Is your feature request related to a problem? Please describe.

If scan is clear, command line returns nothing. Safe to assume the scan was clean....but would like CLI feedback.

## Describe the solution you'd like

CLI returns when no errors/issues:

'date:time- 100% Clean'

**Comment by tarkatronic** [comment]
I think this makes sense. By default, we can print out some kind of success message.
`All clear. No secrets detected.`
We can also add a `-q/--quiet` flag to suppress that ouput.

This also goes hand in hand with #11 and #37. I think we need generally just a revamp of our outputs.

**Comment by janerikcarlsen** [comment]
Taking this on together with https://github.com/godaddy/tartufo/issues/43
