### ISSUE TITLE
Report out of the list of exclusions

### ISSUE THREAD

**Issue by tcostello-godaddy** [godaddy/tartufo#43]
## Feature Request

I would like a CLI output and/or a output.txt file generate with the list of exclusions when the scan was run.

## Is your feature request related to a problem? Please describe.

When run the scan with exclusions and it is clean, no output to CLI.

## Describe the solution you'd like

Output to CLI:
date:time
'02/20/2020 - 100% Clean'
List of exclusions:
excludethisfile.txt

**Comment by tarkatronic** [comment]
Would this be just a printout of the patterns which were used for exclusions, or a printout of the actual files which matched those patterns?

I think this makes sense in 2 particular scenarios:

1. Add this to the JSON output. That's pretty much a no-brainer.
2. Add a `-v/--verbose` flag, and this would be the first thing exposed by that.
