### ISSUE TITLE
Running tartufo from docker does not scan target repo

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#44]
## 🐛 Bug Report

Running Tartufo from the docker image in the recommended manner results in Tartufo scanning itself in the docker image, not the target repository

## To Reproduce

> docker pull godaddy/tartufo
> docker run -t --rm -v "$PWD:/git" godaddy/tartufo --repo_path .

results in tartufo scanning the tartufo directory in the container, not the mounted repo.

Changing the invocation to reference the mountpoint correctly fixes the scan target issue, but leads to failing ssh

> docker run -t --rm -v "$PWD:/git" godaddy/tartufo --repo-path /git
> Traceback (most recent call last):
> ...
>   cmdline: git fetch -v origin
>   stderr: 'error: cannot run ssh: No such file or directory

## Expected Behavior

Docker container should be able to execute the above command successfully and without user interaction

## Code Example
At minimum requires the addition of 
> apk add openssh-client

to the Dockerfile

**Comment by janerikcarlsen** [comment]
Added https://github.com/godaddy/tartufo/pull/45 to make the docker image work properly for pre-commit hooks. 
This PR does not solve ssh-agent authentication to github repositories for full history scan.

**Comment by c-jcarlsen-godaddy** [comment]
PR merged, suggest closing this issue

**Comment by tarkatronic** [comment]
Resolved in #45 & #46
