### ISSUE TITLE
Normalizing pathnames to generate identical signatures from both Windows and Linux

### ISSUE THREAD

**Issue by sql-sith** [godaddy/tartufo#456]
### Tartufo on WIndows produces different signatures than Tartufo on Linux does

Some of my coworkers only use Windows. They run `tartufo` against their code in `pwsh.exe` and then add `exclude-signatures` until they get a clean run. However, they now have a CICD component that requires them to pass a mandatory `tartufo` run. The problem is that the `tartufo` creates different signatures for the same findings depending on which operating system runs `tartufo`. This seems to be because a file referenced as `repo_root/folder1/file1.py` in Linux will be referenced as `repo_root\folder1\file1.py` in Windows. Since the filename is one of the inputs for creating a signature, Windows and Linux versions of `tartufo` create different signatures.

### Why it matters

These Windows programmers run `tartufo` in `wsl` to create signatures that will be recognized by the mandatory CICD run of `tartufo`, but would like to be able to stay within their normal working environment. More on the disruptiveness and possible consequences for them will be discussed later.

### Optionally force filenames to match Linux formats for the purpose of signature generation

I would like `tartufo` to allow an optional conversion of Windows filenames to their Linux equivalents whenever the comparison is within a git repository. This should be feasible because, within a repository, the root of a filesystem is never referenced, so you don't have to worry about how to represent something like `C:\`. Instead, the repo's root is treated as the root of a `git` file namespace.

My proposed solution is a command-line option, possibly `--force-linux-pathnames`, that would cause `tartufo` to generate the equivalent Linux path and file for Windows files so that the signatures from `tartufo` will be platform-agnostic between Windows and Linux.

### What our developers are currently doing

We've considered having the developers use `wsl` for running `tartufo` and building their signature exceptions based on this. This is, in fact, the procedure they are now using. 

### Why we think this would be better

However, this is disruptive to their workflow since it is the only thing they do (95-ish percent of the time) in a Linux environment, and it increases the chance that they might accidentally switch the line endings or encodings of their files in a detrimental way. 

## Teachability, Documentation, Adoption, Migration Strategy

```
tartufo --help

--force-linux-pathnames
                                 This option will change the character used as a folder separator, if 
                                 necessary, so that the filenames used by tartufo when creating 
                                 signatures match Linux naming conventions. This is helpful if you
                                 work on multiple operating systems and need signatures created
                                 on all of them to be identical.

```

**Comment by cleonard-godaddy** [comment]
I am having trouble duplicating this in version 4. Closing for now while I reassess.

**Comment by sql-sith** [comment]
I'm having trouble reproducing this on version 4. Closing while I reassess.
