### ISSUE TITLE
Tartufo looks for config in current directory even when using --config

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/tartufo#469]
## 🐛 Bug Report

If tartufo is executed `tartufo --config /path/to/config scan-local-repo .` It still imports any tartufo config present in the current directory in addition to the config specified in `/path/to/config`

## To Reproduce

Using the tartufo repository itself as an example:

1. Copy some of the tartufo stuff out of `pyproject.toml` into a new `foo.toml` (leave all of the existing stuff alone so that what you are trying to look at doesn't get washed out with findings)
2. Run `tartufo -v --config foo.toml scan-local-repo .`

## Expected Behavior

It should only use the config in `foo.toml`

## Environment

Tartufo v4.0.1

**Comment by jsimmons1-godaddy** [comment]
Note that I have a clarification in https://github.com/godaddy/tartufo/pull/473#issuecomment-1483083212 related to this issue. In short: it uses the config in the current directory only because `.` (the current directory) is the target of the scan. If `foo/bar/baz` is the target of the scan, it would use the tartufo.toml from there (assuming one exists).

**Comment by mgaspar-godaddy** [comment]
Another issue related to this that I've found is even though the local config is still read when another config is provided via `--config` some things like additional `rule-patterns` in the local config do not get included.

For example, if I have a local config which defines a rule-patterns section to catch additional regex items to flag them as potentially sensitive information, and then I run tartufo with `--config ~/path/to/some/other/config.toml` the rule-patterns in my local config aren't read in. This can result in false negatives where a user thinks their rules are getting loaded and nothing was found when the reality is those rules didn't get loaded and sensitive data is being missed.

I was able to verify this by running tartufo with the `-vvv` option to increase verbosity which prints out a line like `Regex rules were initialized as:` which contains an object that includes all of the loaded rules.

`tartufo -vvv --no-entropy scan-local-repo .` <- should show custom rules defined in rule-patterns within the local tartufo.toml
`tartufo -vvv --no-entropy --config ~/path/to/config.toml scan-local-repo .` <- should show missing custom rules from the local tartufo.toml

**Comment by emayuri-godaddy** [comment]
> Another issue related to this that I've found is even though the local config is still read when another config is provided via `--config` some things like additional `rule-patterns` in the local config do not get included.
> 
> For example, if I have a local config which defines a rule-patterns section to catch additional regex items to flag them as potentially sensitive information, and then I run tartufo with `--config ~/path/to/some/other/config.toml` the rule-patterns in my local config aren't read in. This can result in false negatives where a user thinks their rules are getting loaded and nothing was found when the reality is those rules didn't get loaded and sensitive data is being missed.
> 
> I was able to verify this by running tartufo with the `-vvv` option to increase verbosity which prints out a line like `Regex rules were initialized as:` which contains an object that includes all of the loaded rules.
> 
> `tartufo -vvv --no-entropy scan-local-repo .` <- should show custom rules defined in rule-patterns within the local tartufo.toml `tartufo -vvv --no-entropy --config ~/path/to/config.toml scan-local-repo .` <- should show missing custom rules from the local tartufo.toml

@mgaspar-godaddy This looks like a bug in Tartufo that probably got introduced during the transition from [--rules ](https://github.com/godaddy/tartufo/issues/256). As this is different from the existing issue, I have created a task to track and fix this https://github.com/godaddy/tartufo/issues/476

**Comment by mgaspar-godaddy** [comment]
Hey @emayuri-godaddy, I added a comment to https://github.com/godaddy/tartufo/issues/476#issuecomment-1483426445, but I think the issue I am seeing is related to this issue and potentially other issues around how multiple config files get merged.
