### ISSUE TITLE
Convert CI/CD to GitHub Actions

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#58]
## Is your feature request related to a problem? Please describe.

We currently use TravisCI for our builds. It's got a whole host of problems; far too many to go into right now. Suffice to say, we don't want to use it anymore.

## Describe the solution you'd like

All of the current functionality performed by Travis should be replicated by GitHub Actions. As an added bonus, we may be able to get the individual tests steps (different tox environments) listed as separate build checks, making it easier to discover exactly what failed.

## Describe alternatives you've considered

We've looked at CircleCI, but it's had its own set of problems with reliability, and recently on asherah we've had issue with visibility of builds. Plus, GitHub Actions is built right in here, and works *super* well.

## Teachability, Documentation, Adoption, Migration Strategy

Very little should need to be changed in the docs for this. In fact, I'm not sure our CI/CD pipeline is documented at all right now. But we can leave that for another issue...

**Comment by janerikcarlsen** [comment]
Happy to take this on
