### ISSUE TITLE
Support scanning of uncommitted blobs to allow for pre-commit hook use

### ISSUE THREAD

**Issue by mxhenry** [godaddy/tartufo#7]
ISBAT: Scan a git blob during a pre-commit hook call to find violations before they are committed to the local repository clone

**Comment by rscottbailey** [comment]
Pull request godaddy/tartufo-archive#3 does refactoring in support of this objective. These changes enable print_results(), find_entropy() and find_regex() [name change] to be called without any git context. They then become useful for pre-commit scans, scans of arbitrary input files, scans of arbitrary stdin, or whatever.

**Comment by rscottbailey** [comment]
Also see https://stackoverflow.com/questions/57563400/how-to-get-staged-diffs-for-commit for blocker on the last piece of the pre-commit support work (namely torturing GitPython to provide the relevant differences).

**Comment by rscottbailey** [comment]
godaddy/tartufo-archive#8 implements this functionality, crudely. Until the GitPython issue mentioned above is fixed, it works by scanning the complete content of each staged file. If the files are non-trivial in size, scan overhead is a lot more than it needs to be and generated output is hard to deal with since each "diff" actually is the complete body of the file.

**Comment by rscottbailey** [comment]
I found the required workaround and PR godaddy/tartufo-archive#8 is in good shape now for merging in my admittedly biased opinion. Packaging for use in this context is left as an exercise for the student LOL.

**Comment by mxhenry-godaddy** [comment]
@rscottbailey could you fork off of https://github.secureserver.net/mxhenry/guidelines and add a section to ./Standards-Best-Practices/CodeScan/truffleHog.md outlining how to use tartufo with pre-commit hooks. There is already a section for pre-push hooks. Thanks!

**Comment by rscottbailey** [comment]
Noted... It's at the head of my to-do list (although I'm barely a day into my accumulated inbox cruft!)
