### ISSUE TITLE
Support Scanning Directory

### ISSUE THREAD

**Issue by dclayton-godaddy** [godaddy/tartufo#83]
## Is your feature request related to a problem? Please describe.

We would like to scan the current directory. From this scan, we can remediate any active secret usage and allow tools like `bfg` to clean git history. We only are about the secrets currently being used.

## Describe the solution you'd like

A CLI command like `tartufo scan .`.

## Describe alternatives you've considered

Rumor has it we can use `bfg` to temporarily clean history, then rerun tartufo, but that is painful.

## Teachability, Documentation, Adoption, Migration Strategy

Something like, "To run a scan against a directory, use `tartufo scan [{options}] {directory}`."

**Comment by tarkatronic** [comment]
Just to be clear, are you requesting the ability to scan a local directory which *is* a git repo, or one which *is not* a git repo?

The former has always been functionality of `truffleHog`/`tartufo`, although it was a bit confusing previously (It was invoked via `--repo-path`). Now it is provided via `tartufo scan-local-repo .`.

If you mean the latter, scanning a folder which *is not* a git repo, then I agree I absolutely want to add something like `tartufo scan-folder`!

**Comment by dclayton-godaddy** [comment]
Ya, a directory. `scan-folder` will work too.

**Comment by tarkatronic** [comment]
Okay yeah this is definitely something I want to add, and part of the reason behind splitting into sub-commands! I'm not sure when this will get implemented, but glad to have a ticket in here for it!
