### ISSUE TITLE
If a `pyproject.toml` is present, `tartufo.toml` is never checked for configuration

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#86]
## 🐛 Bug Report

In Python projects, the `pyproject.toml` file is becoming somewhat ubiquitous. It is being used for configuration of all forms of tooling, and even `tartufo` allows users to place their config in this file. However, if users opt to, instead, put their `tartufo` config into a `tartufo.toml` file when they already have a `pyproject.toml` file, this will have no effect.

This is especially problematic once users start using hash-based signatures. These signatures, themselves, will get detected and reported as high entropy strings, meaning that the `tartufo` configuration file should be ignored. In practice, it should generally be perfectly acceptable to ignore the `tartufo.toml`, but ignoring an entire `pyproject.toml`, which could have some legitimate secrets, should be avoided.

## To Reproduce

* Create a `pyproject.toml` file, even an empty one
* Create a `tartufo.toml` file, with a `[tool.tartufo]` section and actual config rules
* Run `tartufo`
* The configuration found in the `tartufo.toml` will not be read nor used.

## Expected Behavior

If a `tartufo.toml` is present, that should likely take precedence over `pyproject.toml`. Also, a `pyproject.toml` with no `[tool.tartufo]` section should not prevent the `tartufo.toml` from being read.

The simplest and most obvious fix might just be to swap the order in which the files are checked: Check for a `tartufo.toml` first; if that doesn't exist, check for a `pyproject.toml`. This will need to be done in both the `config.read_pyproject.toml`, and in the code that checks repositories for their local exclusion rules. (Does this still exist? Did this get removed in the work up to 2.0?)

**Comment by Rashmi-K-A** [comment]
Hey @tarkatronic, can I take this up?

**Comment by tarkatronic** [comment]
Hi @Rashmi-K-A! Yes, I would happily welcome a PR for this issue! I think the real trick to this one will be getting good tests in place to ensure that the `tartufo.toml` takes precedence.

Thank you for the offer to help! I look forward to seeing what you come up with.
