### ISSUE TITLE
Allow Entropy b64/hex Score Override

### ISSUE THREAD

**Issue by dclayton-godaddy** [godaddy/tartufo#89]
## Is your feature request related to a problem? Please describe.

Add the ability to override the current hard coded entropy b64/hex scores. This will enable us to specify the level of entropy risk.

## Describe the solution you'd like

Add `b64/hex` entropy options to toml config files or CLI.

**Comment by tarkatronic** [comment]
Specifically, we want to be able to override the values at https://github.com/godaddy/tartufo/blob/9e1fc5b577bf56cca1dd020e66bfec21ff1b96d4/tartufo/scanner.py#L207 and https://github.com/godaddy/tartufo/blob/9e1fc5b577bf56cca1dd020e66bfec21ff1b96d4/tartufo/scanner.py#L213 on the command line, while keeping the same default values.

**Comment by jgowdy** [comment]
👍

**Comment by tarkatronic** [comment]
Fixed via #223
