### ISSUE TITLE
Would be good to have an option to exclude commits related to adding/removing git submodules

### ISSUE THREAD

**Issue by sgore-godaddy** [godaddy/tartufo#96]
## Feature Request
Would be good to have an option to exclude commits related to adding/removing git submodules

## Is your feature request related to a problem? Please describe.

When adding submodules, git adds a diff which includes the commit hash of the submodule. similar to following:

```
@@ -0,0 +1 @@\n+Subproject commit 821b2b1037dd11d4afb61e1eed870ca4e2fbf608\n
```

This commit is getting reported by tartufo scan.

an example of issue reported by tartufo:
```
{
  "file_path": "packages/a-submodule-package",
  "matched_string": "821b2b1037dd11d4afb61e1eed870ca4e2fbf608",
  "diff": "@@ -0,0 +1 @@\n+Subproject commit 821b2b1037dd11d4afb61e1eed870ca4e2fbf608\n",
  "signature": "eb27ebd567f1d17149e4cc9b2221490e0d5b651c121f06c22a0364444ce8b28c",
  "issue_type": "High Entropy",
  "issue_detail": null,
  "commit_time": "2019-11-07 15:22:22",
  "commit_message": "add submodule",
  "commit_hash": "e10234695b3cdbd79cc9575111c730cd2863bf3f",
  "branch": "origin/master"
}
```

More information on git submodules can be found here - https://git-scm.com/book/en/v2/Git-Tools-Submodules 

## Describe the solution you'd like

The diff matches the following pattern: 
```@@ -0,0 +1 @@\n+Subproject commit 821b2b1037dd11d4afb61e1eed870ca4e2fbf608\n```

I think we tartufo excludes this particular diff pattern it may solve the issue.
Also look at https://git-scm.com/book/en/v2/Git-Tools-Submodules to check if there is a better alternative.

## Describe alternatives you've considered

As a workaround I excluded the submodules paths (Of the directory, not the files within the directories).

**Comment by wescran** [comment]
Hi I would like to help with this. I am thinking of implementing a regex exclusion pattern to check against the diff in commit history

**Comment by tarkatronic** [comment]
Hi @wescran, thank you for the offer to hop in! I think that is definitely one possible solution to this problem; before diving in with a solution though, I would like to explore if there are any other possibilities.

What you are suggesting would best be implemented, I believe, by way of a more wholistic solution to #87. And that would be fantastic! Regex-based exclusion patterns would be wonderful to have, and we could implement a default set of them, including one for submodules.

The other option I would like to explore though, which I think might be preferable, is to see if there is any kind of metadata in a commit to tell us that it is a submodule. If we can, as we iterate through the files in a commit, positively identify and skip over submodules via a specific flag or some similar piece of metadata, I think that would be ideal. It would be a very specific fix, more easily testable, and would introduce less overhead than an extra regular expression check would.

I haven't looked into whether this second option is even a possibility yet, but https://gitpython.readthedocs.io/en/stable/ should contain some clues; that is the underlying library we use for interacting with git!

Thank you again for offering to take this on!

**Comment by wescran** [comment]
Hello again!

I spent some time going over the documentation and scouring the web for some answers. From what I could find, there doesn't seem to be any type of metadata in a commit that would tell us immediately if it was for creating a submodule. From reading the git documentation on submodules, when a submodule is committed a [special model of `160000` is created](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for it. So maybe there is a possibility of checking the [`file_mode` of a blob](https://gitpython.readthedocs.io/en/stable/reference.html#git.objects.blob.Blob.file_mode) for that value when yielding `types.Chunk`. Other than that I am not sure if there is another way besides implementing a regex solution.

**Comment by wescran** [comment]
Just an update again!

So in your `GitScanner` method `_iter_diff_index` the diff path is retrieved from the diff index between commits. From that diff object you can access the [file mode of the object](https://gitpython.readthedocs.io/en/stable/reference.html#git.diff.Diff.a_mode). As mentioned in my previous comment, git designates a special file mode of `160000` for submodules and this will always be seen in the initial submodule commit. 

Based on this I think a conditional could be added to the method to check the file mode. Something like:
```python
file_mode = diff.b_mode if diff.b_mode else diff.a_mode
if file_mode == 0o160000:
    continue
```
This could also be moved in to the `ScannerBase` `should_scan` method but another argument would need to pass in as only the `file_path` is passed in. Let me know you thoughts on this and I can get started on a PR.

Thanks!
